"""Excel 函数目录 — 200+ 函数按场景组织。

每个条目包含：英文名、中文名、分类、语法、中文描述、示例、常见用例、陷阱。
这是 prompt 构建的核心知识源。
"""

from dataclasses import dataclass, field
from typing import Optional

CATEGORY_STATS = "数据汇总与统计"
CATEGORY_FINANCE = "财务与业务计算"
CATEGORY_DATA = "数据处理与清洗"


@dataclass
class FunctionEntry:
    name: str
    zh_name: str
    category: str
    syntax: str
    description_zh: str
    example_zh: str
    common_use_cases: list[str] = field(default_factory=list)
    pitfalls: list[str] = field(default_factory=list)
    keywords: list[str] = field(default_factory=list)


# ============================================================
# 数据汇总与统计
# ============================================================

STATS_FUNCTIONS: list[FunctionEntry] = [
    FunctionEntry(
        name="SUM",
        zh_name="求和",
        category=CATEGORY_STATS,
        syntax="SUM(number1, [number2], ...)",
        description_zh="计算一组数值的总和。最基础的聚合函数。",
        example_zh="=SUM(B2:B100) 计算B2到B100所有数值的总和",
        common_use_cases=["求总和", "合计", "加起来", "汇总金额", "求和"],
        pitfalls=["忽略文本和逻辑值", "空单元格自动跳过"],
        keywords=["sum", "求和", "合计", "总数", "汇总", "加起来"],
    ),
    FunctionEntry(
        name="SUMIF",
        zh_name="条件求和",
        category=CATEGORY_STATS,
        syntax="SUMIF(range, criteria, [sum_range])",
        description_zh="对满足单一条件的单元格求和。range 是判断区域，criteria 是条件，sum_range 是实际求和的区域（可选，默认与 range 相同）。",
        example_zh='=SUMIF(E5:E51,"一线",G5:G51) 计算层级为"一线"的所有岗位的薪资中位数之和',
        common_use_cases=["按条件求和", "分类汇总", "统计某部门总额"],
        pitfalls=["criteria 使用文本时需加引号", "如果 sum_range 省略，则对 range 求和"],
        keywords=["sumif", "条件求和", "按条件汇总", "分类合计"],
    ),
    FunctionEntry(
        name="SUMIFS",
        zh_name="多条件求和",
        category=CATEGORY_STATS,
        syntax="SUMIFS(sum_range, criteria_range1, criteria1, [criteria_range2, criteria2], ...)",
        description_zh="对满足多个条件的单元格求和。第一个参数是求和区域，后面成对出现条件区域和条件。支持最多127个条件对。",
        example_zh='=SUMIFS(G5:G51,E5:E51,"一线",D5:D51,"装配工") 计算一线装配工的薪资中位数之和',
        common_use_cases=["多条件汇总", "按部门和岗位求和", "复杂筛选求和"],
        pitfalls=["sum_range 是第一个参数（与 SUMIF 不同！）", "所有条件必须同时满足（AND 关系）"],
        keywords=["sumifs", "多条件求和", "多个条件汇总", "分类汇总"],
    ),
    FunctionEntry(
        name="AVERAGE",
        zh_name="平均值",
        category=CATEGORY_STATS,
        syntax="AVERAGE(number1, [number2], ...)",
        description_zh="计算一组数值的算术平均值。忽略空单元格和文本。",
        example_zh="=AVERAGE(G5:G51) 计算G5到G51所有薪资中位数的平均值",
        common_use_cases=["求平均", "均值", "平均水平", "平均工资"],
        pitfalls=["忽略文本和逻辑值", "0 值会被计入"],
        keywords=["average", "平均值", "平均", "均值"],
    ),
    FunctionEntry(
        name="AVERAGEIF",
        zh_name="条件平均值",
        category=CATEGORY_STATS,
        syntax="AVERAGEIF(range, criteria, [average_range])",
        description_zh="计算满足单一条件的单元格的平均值。",
        example_zh='=AVERAGEIF(E5:E51,"技术",G5:G51) 计算技术岗位的平均薪资中位数',
        common_use_cases=["按条件求平均", "某类别平均薪资"],
        pitfalls=["与 AVERAGEIFS 参数顺序不同"],
        keywords=["averageif", "条件平均", "分类均值"],
    ),
    FunctionEntry(
        name="COUNT",
        zh_name="计数（数值）",
        category=CATEGORY_STATS,
        syntax="COUNT(value1, [value2], ...)",
        description_zh="统计包含数值的单元格数量。只计算数字、日期和代表数字的文本。",
        example_zh="=COUNT(G5:G51) 统计G列有多少个数值单元格",
        common_use_cases=["统计有数据的行数", "计数"],
        pitfalls=["不统计纯文本", "不统计空单元格"],
        keywords=["count", "计数", "个数", "数量"],
    ),
    FunctionEntry(
        name="COUNTA",
        zh_name="计数（非空）",
        category=CATEGORY_STATS,
        syntax="COUNTA(value1, [value2], ...)",
        description_zh="统计非空单元格的数量。计算包含任何类型数据的单元格（包括文本、数字、错误值、逻辑值）。",
        example_zh="=COUNTA(D5:D51) 统计D列有多少个非空单元格",
        common_use_cases=["统计总记录数", "看有多少条数据"],
        pitfalls=["会统计包含公式返回空字符串的单元格"],
        keywords=["counta", "非空计数", "记录数", "条数"],
    ),
    FunctionEntry(
        name="COUNTIF",
        zh_name="条件计数",
        category=CATEGORY_STATS,
        syntax="COUNTIF(range, criteria)",
        description_zh="统计满足单一条件的单元格数量。",
        example_zh='=COUNTIF(E5:E51,"一线") 统计一线岗位的数量',
        common_use_cases=["按条件计数", "统计某类别数量"],
        pitfalls=["支持通配符 * 和 ?"],
        keywords=["countif", "条件计数", "统计个数"],
    ),
    FunctionEntry(
        name="COUNTIFS",
        zh_name="多条件计数",
        category=CATEGORY_STATS,
        syntax="COUNTIFS(criteria_range1, criteria1, [criteria_range2, criteria2], ...)",
        description_zh="统计满足多个条件的单元格数量。",
        example_zh='=COUNTIFS(E5:E51,"一线",F5:F51,">=5000") 统计薪资范围≥5000的一线岗位数量',
        common_use_cases=["多条件计数", "统计符合多个要求的记录"],
        pitfalls=["所有条件必须同时满足（AND 关系）"],
        keywords=["countifs", "多条件计数"],
    ),
    FunctionEntry(
        name="MAX",
        zh_name="最大值",
        category=CATEGORY_STATS,
        syntax="MAX(number1, [number2], ...)",
        description_zh="返回一组数值中的最大值。",
        example_zh="=MAX(G5:G51) 找出最高薪资中位数",
        common_use_cases=["找最大值", "最高值", "最大值"],
        pitfalls=["忽略文本和逻辑值"],
        keywords=["max", "最大值", "最高", "最大"],
    ),
    FunctionEntry(
        name="MIN",
        zh_name="最小值",
        category=CATEGORY_STATS,
        syntax="MIN(number1, [number2], ...)",
        description_zh="返回一组数值中的最小值。",
        example_zh="=MIN(G5:G51) 找出最低薪资中位数",
        common_use_cases=["找最小值", "最低值"],
        pitfalls=["忽略文本和逻辑值"],
        keywords=["min", "最小值", "最低", "最小"],
    ),
    FunctionEntry(
        name="MEDIAN",
        zh_name="中位数",
        category=CATEGORY_STATS,
        syntax="MEDIAN(number1, [number2], ...)",
        description_zh="返回一组数值的中位数。中位数比平均值更能抵抗极端值的影响。",
        example_zh="=MEDIAN(G5:G51) 计算所有薪资中位数的中位数（中间水平）",
        common_use_cases=["计算中位数", "中间值", "中位薪资"],
        pitfalls=["如果数值个数为偶数，返回中间两个数的平均值"],
        keywords=["median", "中位数", "中间值", "中位"],
    ),
    FunctionEntry(
        name="LARGE",
        zh_name="第k大值",
        category=CATEGORY_STATS,
        syntax="LARGE(array, k)",
        description_zh="返回数据集中第k大的值。k=1是最大值，k=2是第二大值。",
        example_zh="=LARGE(G5:G51,3) 找出薪资中位数第三高的值",
        common_use_cases=["找前几名", "排名第几的值", "最高前三"],
        pitfalls=["k必须大于0且不超过数据个数"],
        keywords=["large", "第k大", "前几名", "最高几位"],
    ),
    FunctionEntry(
        name="SMALL",
        zh_name="第k小值",
        category=CATEGORY_STATS,
        syntax="SMALL(array, k)",
        description_zh="返回数据集中第k小的值。",
        example_zh="=SMALL(G5:G51,1) 找出最低薪资中位数（等同于MIN）",
        common_use_cases=["找最低几位", "第几小的值"],
        pitfalls=["k必须大于0且不超过数据个数"],
        keywords=["small", "第k小", "最低几位"],
    ),
    FunctionEntry(
        name="RANK",
        zh_name="排名",
        category=CATEGORY_STATS,
        syntax="RANK(number, ref, [order])",
        description_zh="返回某数值在一组数值中的排名。order=0（默认）为降序排名，order=1为升序。",
        example_zh="=RANK(G5,$G$5:$G$51,0) 计算G5在G列中的降序排名",
        common_use_cases=["排名", "排第几", "名次"],
        pitfalls=["ref 建议用绝对引用 $A$1:$A$100", "相同值会得到相同排名，下一个会跳号"],
        keywords=["rank", "排名", "名次", "排第几"],
    ),
    FunctionEntry(
        name="RANK.EQ",
        zh_name="排名（同值同排名）",
        category=CATEGORY_STATS,
        syntax="RANK.EQ(number, ref, [order])",
        description_zh="与RANK功能相同，返回排名。相同值得到相同排名，后续跳过。",
        example_zh="=RANK.EQ(G5,$G$5:$G$51)",
        common_use_cases=["排名"],
        pitfalls=["建议用RANK.AVG获取平均排名避免跳号"],
        keywords=["rank.eq", "排名"],
    ),
    FunctionEntry(
        name="SUBTOTAL",
        zh_name="分类汇总",
        category=CATEGORY_STATS,
        syntax="SUBTOTAL(function_num, ref1, [ref2], ...)",
        description_zh="对筛选后的可见数据执行汇总计算。function_num 1-11包含隐藏行，101-111忽略隐藏行。常用：9/109=SUM，1/101=AVERAGE，2/102=COUNT。",
        example_zh="=SUBTOTAL(9,G5:G51) 对G列筛选后可见的数据求和",
        common_use_cases=["筛选后汇总", "可见数据求和", "分类汇总"],
        pitfalls=["需要配合筛选使用才有意义", "不忽略手动隐藏的行（需用109等）"],
        keywords=["subtotal", "筛选求和", "分类汇总", "可见单元格"],
    ),
    FunctionEntry(
        name="STDEV.P",
        zh_name="总体标准差",
        category=CATEGORY_STATS,
        syntax="STDEV.P(number1, [number2], ...)",
        description_zh="计算整个总体的标准差，假设数据代表整个总体。",
        example_zh="=STDEV.P(G5:G51) 计算薪资中位数的总体标准差",
        common_use_cases=["标准差", "波动幅度", "离散程度"],
        pitfalls=["样本数据应用 STDEV.S"],
        keywords=["stdev", "标准差", "波动", "离散"],
    ),
    FunctionEntry(
        name="STDEV.S",
        zh_name="样本标准差",
        category=CATEGORY_STATS,
        syntax="STDEV.S(number1, [number2], ...)",
        description_zh="计算样本的标准差，适用于从总体中抽样的情况。",
        example_zh="=STDEV.S(G5:G51) 计算薪资中位数的样本标准差",
        common_use_cases=["样本标准差", "数据波动分析"],
        pitfalls=["总体数据应用 STDEV.P"],
        keywords=["stdev.s", "标准差", "样本"],
    ),
    FunctionEntry(
        name="QUARTILE.INC",
        zh_name="四分位数",
        category=CATEGORY_STATS,
        syntax="QUARTILE.INC(array, quart)",
        description_zh="返回数据集的四分位数。quart 取值：0=最小值，1=第一四分位数(25%)，2=中位数(50%)，3=第三四分位数(75%)，4=最大值。",
        example_zh="=QUARTILE.INC(G5:G51,3) 计算薪资中位数的第三四分位数（75%分位）",
        common_use_cases=["分位数分析", "薪酬分位", "四分位距"],
        pitfalls=["quart 必须是 0-4 的整数"],
        keywords=["quartile", "四分位数", "分位数", "分位"],
    ),
    FunctionEntry(
        name="MODE.SNGL",
        zh_name="众数",
        category=CATEGORY_STATS,
        syntax="MODE.SNGL(number1, [number2], ...)",
        description_zh="返回数据中出现频率最高的值（众数）。",
        example_zh="=MODE.SNGL(G5:G51) 找出最常见的薪资中位数值",
        common_use_cases=["找最常见的值", "众数"],
        pitfalls=["如果有多个众数，只返回最先出现的"],
        keywords=["mode", "众数", "最常见"],
    ),
    FunctionEntry(
        name="AGGREGATE",
        zh_name="聚合函数（多功能）",
        category=CATEGORY_STATS,
        syntax="AGGREGATE(function_num, options, ref1, [ref2], ...)",
        description_zh="多功能聚合函数，支持19种运算（SUM/AVERAGE/COUNT/MAX/MIN等），可选择忽略错误值、隐藏行、嵌套SUBTOTAL等。",
        example_zh="=AGGREGATE(1,6,G5:G51) 忽略错误值计算平均值（1=AVERAGE, 6=忽略错误值）",
        common_use_cases=["忽略错误值汇总", "复杂聚合"],
        pitfalls=["function_num 和 options 需要记忆对应数字"],
        keywords=["aggregate", "聚合", "忽略错误汇总"],
    ),
]

# ============================================================
# 财务与业务计算
# ============================================================

FINANCE_FUNCTIONS: list[FunctionEntry] = [
    FunctionEntry(
        name="PMT",
        zh_name="贷款月供",
        category=CATEGORY_FINANCE,
        syntax="PMT(rate, nper, pv, [fv], [type])",
        description_zh="计算固定利率下贷款的每期还款额（等额本息）。rate是每期利率，nper是总期数，pv是贷款本金。结果默认为负数（支出）。",
        example_zh="=PMT(4.9%/12,240,1000000) 计算100万贷款、年利率4.9%、20年期的月供",
        common_use_cases=["计算月供", "贷款还款", "按揭计算"],
        pitfalls=["利率和期数单位必须一致（月利率配月数）", "结果为负数代表支出"],
        keywords=["pmt", "月供", "贷款", "还款", "按揭", "等额本息"],
    ),
    FunctionEntry(
        name="PV",
        zh_name="现值",
        category=CATEGORY_FINANCE,
        syntax="PV(rate, nper, pmt, [fv], [type])",
        description_zh="基于固定利率和等额分期付款，计算投资或贷款的现值。",
        example_zh="=PV(5%/12,36,-1000) 计算每月投入1000元、3年期、年化5%的现值",
        common_use_cases=["计算现值", "投资价值评估", "折现"],
        pitfalls=["负数代表支出，正数代表收入"],
        keywords=["pv", "现值", "折现", "投资价值"],
    ),
    FunctionEntry(
        name="FV",
        zh_name="终值",
        category=CATEGORY_FINANCE,
        syntax="FV(rate, nper, pmt, [pv], [type])",
        description_zh="基于固定利率和等额分期付款，计算投资的未来值（终值）。",
        example_zh="=FV(5%/12,36,-1000,0) 每月存1000元，年化5%，3年后的终值",
        common_use_cases=["计算到期本息", "储蓄计划", "投资回报"],
        pitfalls=["利率和期数单位一致"],
        keywords=["fv", "终值", "未来值", "到期金额", "储蓄"],
    ),
    FunctionEntry(
        name="NPV",
        zh_name="净现值",
        category=CATEGORY_FINANCE,
        syntax="NPV(rate, value1, [value2], ...)",
        description_zh="使用贴现率计算一系列现金流的净现值。现金流按时间均匀分布。",
        example_zh="=NPV(8%,-10000,3000,4000,5000,3000) 计算贴现率8%下投资项目的净现值",
        common_use_cases=["项目评估", "投资回报分析", "净现值法"],
        pitfalls=["NPV 假设现金流发生在每期期末", "第一期现金流不折现（从第二期开始）"],
        keywords=["npv", "净现值", "贴现", "项目评估", "投资分析"],
    ),
    FunctionEntry(
        name="IRR",
        zh_name="内部收益率",
        category=CATEGORY_FINANCE,
        syntax="IRR(values, [guess])",
        description_zh="计算一系列现金流的内部收益率。IRR 是使 NPV=0 的贴现率。",
        example_zh="=IRR(B2:B6) 计算B2到B6现金流（含初始投资负值）的内部收益率",
        common_use_cases=["计算投资回报率", "项目收益率", "内部报酬率"],
        pitfalls=["必须包含至少一个正数和一个负数", "可能有多解"],
        keywords=["irr", "内部收益率", "回报率", "收益率"],
    ),
    FunctionEntry(
        name="XIRR",
        zh_name="不规则现金流内部收益率",
        category=CATEGORY_FINANCE,
        syntax="XIRR(values, dates, [guess])",
        description_zh="计算不规则时间间隔现金流的内部收益率。适合实际业务中非定期现金流。",
        example_zh="=XIRR(B2:B10,A2:A10) 计算A列日期对应B列现金流的内部收益率",
        common_use_cases=["实际项目回报", "不规律投资"],
        pitfalls=["dates 必须是有效的日期格式", "values 必须包含至少一正一负"],
        keywords=["xirr", "内部收益率", "不规律现金流"],
    ),
    FunctionEntry(
        name="RATE",
        zh_name="利率计算",
        category=CATEGORY_FINANCE,
        syntax="RATE(nper, pmt, pv, [fv], [type], [guess])",
        description_zh="计算贷款或投资的每期利率。",
        example_zh="=RATE(240,-6000,1000000)*12 计算100万贷款、月供6000、20年期的年化利率",
        common_use_cases=["计算实际利率", "贷款分析"],
        pitfalls=["结果为每期利率，年化需乘以期数"],
        keywords=["rate", "利率", "年化利率"],
    ),
    FunctionEntry(
        name="NPER",
        zh_name="总期数",
        category=CATEGORY_FINANCE,
        syntax="NPER(rate, pmt, pv, [fv], [type])",
        description_zh="基于固定利率和固定还款额，计算还清贷款需要的总期数。",
        example_zh="=NPER(4.9%/12,-5000,500000)/12 计算50万贷款、月还5000、年利率4.9%需要多少年还清",
        common_use_cases=["计算还款年限", "还贷周期"],
        pitfalls=["结果为总期数，除以12得年数"],
        keywords=["nper", "期数", "还款年限", "还多久"],
    ),
    FunctionEntry(
        name="SLN",
        zh_name="直线折旧",
        category=CATEGORY_FINANCE,
        syntax="SLN(cost, salvage, life)",
        description_zh="按直线法计算固定资产每期折旧额。cost=原值，salvage=残值，life=使用年限。",
        example_zh="=SLN(100000,10000,10) 计算原值10万、残值1万、10年折旧的每年折旧额",
        common_use_cases=["固定资产折旧", "直线法"],
        pitfalls=["所有参数必须使用同一时间单位"],
        keywords=["sln", "折旧", "直线法", "固定资产"],
    ),
    FunctionEntry(
        name="DB",
        zh_name="余额递减折旧",
        category=CATEGORY_FINANCE,
        syntax="DB(cost, salvage, life, period, [month])",
        description_zh="按固定余额递减法计算指定期间的折旧额。前期折旧多、后期少。",
        example_zh="=DB(100000,10000,10,1) 计算第1年的余额递减折旧额",
        common_use_cases=["加速折旧", "固定资产折旧"],
        pitfalls=["第一年的month参数默认为12"],
        keywords=["db", "折旧", "余额递减", "加速折旧"],
    ),
    FunctionEntry(
        name="DDB",
        zh_name="双倍余额递减折旧",
        category=CATEGORY_FINANCE,
        syntax="DDB(cost, salvage, life, period, [factor])",
        description_zh="按双倍余额递减法（或其他倍率）计算折旧。factor默认2（双倍）。",
        example_zh="=DDB(100000,10000,10,1) 双倍余额递减法第1年折旧额",
        common_use_cases=["加速折旧", "税务折旧"],
        pitfalls=["后期折旧低于直线法时应切换"],
        keywords=["ddb", "双倍余额递减", "加速折旧"],
    ),
    FunctionEntry(
        name="VDB",
        zh_name="可变余额递减折旧",
        category=CATEGORY_FINANCE,
        syntax="VDB(cost, salvage, life, start_period, end_period, [factor], [no_switch])",
        description_zh="可变余额递减法，可指定是否在直线法更优时自动切换。",
        example_zh="=VDB(100000,10000,10,0,3) 前3年的可变余额递减折旧总额",
        common_use_cases=["灵活折旧计算"],
        pitfalls=["no_switch=FALSE 时会在直线法更优时自动切换"],
        keywords=["vdb", "折旧", "可变余额"],
    ),
    FunctionEntry(
        name="YIELD",
        zh_name="债券收益率",
        category=CATEGORY_FINANCE,
        syntax="YIELD(settlement, maturity, rate, pr, redemption, frequency, [basis])",
        description_zh="计算定期付息债券的收益率。",
        example_zh="=YIELD(DATE(2026,1,1),DATE(2031,1,1),5%,95,100,2) 计算面值100、买入价95、票息5%、5年期债券的收益率",
        common_use_cases=["债券分析", "固定收益"],
        pitfalls=["日期必须用 DATE 函数或有效的日期序列值"],
        keywords=["yield", "债券收益率", "固定收益"],
    ),
    FunctionEntry(
        name="ACCRINT",
        zh_name="应计利息",
        category=CATEGORY_FINANCE,
        syntax="ACCRINT(issue, first_interest, settlement, rate, par, frequency, [basis], [calc_method])",
        description_zh="计算定期付息债券的应计利息。",
        example_zh="=ACCRINT(DATE(2026,1,1),DATE(2026,7,1),DATE(2026,10,1),5%,1000,2)",
        common_use_cases=["债券利息", "应付利息"],
        pitfalls=["参数较多，建议用 DATE 函数构造日期"],
        keywords=["accrint", "应计利息", "债券利息"],
    ),
    FunctionEntry(
        name="COUPNCD",
        zh_name="下一付息日",
        category=CATEGORY_FINANCE,
        syntax="COUPNCD(settlement, maturity, frequency, [basis])",
        description_zh="返回结算日之后的下一个付息日。",
        example_zh="=COUPNCD(DATE(2026,7,19),DATE(2031,1,1),2)",
        common_use_cases=["债券付息日计算"],
        pitfalls=["返回的是日期序列值，需设置日期格式"],
        keywords=["coupncd", "付息日", "债券"],
    ),
    FunctionEntry(
        name="EFFECT",
        zh_name="实际年利率",
        category=CATEGORY_FINANCE,
        syntax="EFFECT(nominal_rate, npery)",
        description_zh="将名义年利率转换为实际年利率（考虑复利次数）。",
        example_zh="=EFFECT(5%,12) 名义年利率5%、月复利的实际年利率",
        common_use_cases=["利率换算", "比较贷款方案"],
        pitfalls=["npery 是每年复利次数"],
        keywords=["effect", "实际利率", "年化利率"],
    ),
    FunctionEntry(
        name="NOMINAL",
        zh_name="名义年利率",
        category=CATEGORY_FINANCE,
        syntax="NOMINAL(effect_rate, npery)",
        description_zh="将实际年利率转换为名义年利率。",
        example_zh="=NOMINAL(5.12%,12) 实际年利率5.12%对应的名义年利率（月复利）",
        common_use_cases=["利率换算"],
        keywords=["nominal", "名义利率"],
    ),
]

# ============================================================
# 数据处理与清洗
# ============================================================

DATA_FUNCTIONS: list[FunctionEntry] = [
    FunctionEntry(
        name="VLOOKUP",
        zh_name="垂直查找",
        category=CATEGORY_DATA,
        syntax="VLOOKUP(lookup_value, table_array, col_index_num, [range_lookup])",
        description_zh="在表格的第一列中查找值，返回该行指定列的值。range_lookup=FALSE为精确匹配，TRUE为近似匹配（要求第一列升序排列）。",
        example_zh='=VLOOKUP("潍坊力创",A5:B51,2,FALSE) 在A列查找"潍坊力创"，返回B列对应值',
        common_use_cases=["根据名称查找", "匹配数据", "查找对应值", "跨表查询"],
        pitfalls=[
            "只能在第一列查找，不能向左查找",
            "插入列会导致 col_index_num 变化",
            "建议用 XLOOKUP 替代（更灵活）",
        ],
        keywords=["vlookup", "查找", "匹配", "查询", "对应"],
    ),
    FunctionEntry(
        name="XLOOKUP",
        zh_name="通用查找（推荐）",
        category=CATEGORY_DATA,
        syntax="XLOOKUP(lookup_value, lookup_array, return_array, [if_not_found], [match_mode], [search_mode])",
        description_zh="新一代查找函数，替代VLOOKUP/HLOOKUP/INDEX+MATCH。可以任意方向查找，精确匹配是默认行为，支持未找到时的默认值。",
        example_zh='=XLOOKUP("装配工",D5:D51,G5:G51,"未找到") 在D列查找"装配工"，返回G列薪资中位数',
        common_use_cases=["任意方向查找", "匹配返回", "跨列查询"],
        pitfalls=["Excel 2021+ 和 Microsoft 365 才支持", "WPS 2019+ 支持"],
        keywords=["xlookup", "查找", "匹配", "通用查找"],
    ),
    FunctionEntry(
        name="INDEX",
        zh_name="索引取值",
        category=CATEGORY_DATA,
        syntax="INDEX(array, row_num, [column_num])",
        description_zh="返回数组中指定行号和列号交叉处的值。常与 MATCH 函数配合使用，实现灵活的二维查找。",
        example_zh="=INDEX(G5:G51,3) 返回G列第3个值（即G7）",
        common_use_cases=["行列定位取值", "配合MATCH实现灵活查找"],
        pitfalls=["单独使用时功能有限，配合MATCH发挥威力"],
        keywords=["index", "索引", "定位取值"],
    ),
    FunctionEntry(
        name="MATCH",
        zh_name="匹配位置",
        category=CATEGORY_DATA,
        syntax="MATCH(lookup_value, lookup_array, [match_type])",
        description_zh="返回查找值在数组中的相对位置（第几个）。match_type: 0=精确匹配，1=小于等于（升序），-1=大于等于（降序）。",
        example_zh='=MATCH("装配工",D5:D51,0) 返回"装配工"在D列的位置',
        common_use_cases=["查找位置", "配合INDEX实现灵活查找", "判断是否存在"],
        pitfalls=["返回的是位置而非值", "常与 INDEX 配合：INDEX+MATCH"],
        keywords=["match", "匹配位置", "第几个"],
    ),
    FunctionEntry(
        name="INDEX+MATCH",
        zh_name="索引匹配组合（灵活查找）",
        category=CATEGORY_DATA,
        syntax="INDEX(return_column, MATCH(lookup_value, lookup_column, 0))",
        description_zh="INDEX 和 MATCH 的组合使用，可以替代 VLOOKUP，支持向左查找，且不受列插入影响。",
        example_zh='=INDEX(G5:G51,MATCH("装配工",D5:D51,0)) 在D列找到"装配工"的位置，返回G列对应薪资',
        common_use_cases=["灵活查找", "向左查找", "不受插入列影响"],
        pitfalls=["比 VLOOKUP 稍复杂", "match_type 通常用 0（精确匹配）"],
        keywords=["index match", "组合查找", "灵活查询"],
    ),
    FunctionEntry(
        name="IF",
        zh_name="条件判断",
        category=CATEGORY_DATA,
        syntax="IF(logical_test, value_if_true, value_if_false)",
        description_zh="根据条件判断返回不同结果。支持嵌套，但嵌套过深建议用 IFS 或 SWITCH。",
        example_zh='=IF(G5>8000,"高薪","普通") 判断薪资中位数是否大于8000',
        common_use_cases=["条件分类", "判断", "二选一"],
        pitfalls=["嵌套 IF 不超过7层（建议用 IFS）", "value_if_false 省略则返回 FALSE"],
        keywords=["if", "如果", "条件", "判断"],
    ),
    FunctionEntry(
        name="IFS",
        zh_name="多条件判断",
        category=CATEGORY_DATA,
        syntax="IFS(condition1, value1, [condition2, value2], ...)",
        description_zh="检查多个条件，返回第一个为 TRUE 的对应值。比嵌套 IF 更清晰。",
        example_zh='=IFS(G5>=10000,"高薪",G5>=6000,"中等",G5<6000,"入门") 多级薪资分类',
        common_use_cases=["多级分类", "分段判断", "评分等级"],
        pitfalls=["如果没有条件为TRUE，返回 #N/A", "条件按顺序检查"],
        keywords=["ifs", "多条件", "多级判断", "分段"],
    ),
    FunctionEntry(
        name="SWITCH",
        zh_name="多值匹配",
        category=CATEGORY_DATA,
        syntax="SWITCH(expression, value1, result1, [value2, result2], ..., [default])",
        description_zh="将表达式与一系列值匹配，返回第一个匹配值对应的结果。适用于精确匹配多个可能值。",
        example_zh='=SWITCH(E5,"一线","基层岗位","技术","技术岗位","职能","管理岗位","其他")',
        common_use_cases=["值映射", "多选一转换", "编码翻译"],
        pitfalls=["最多支持126个值-结果对", "不适用于范围判断（用IFS）"],
        keywords=["switch", "匹配转换", "多值映射"],
    ),
    FunctionEntry(
        name="LEFT",
        zh_name="左截取",
        category=CATEGORY_DATA,
        syntax="LEFT(text, [num_chars])",
        description_zh="从文本左侧开始截取指定数量的字符。",
        example_zh='=LEFT("潍坊力创电子科技",3) 返回"潍坊力"',
        common_use_cases=["提取前缀", "截取固定长度字符"],
        pitfalls=["中文每个字算1个字符"],
        keywords=["left", "左截取", "取左边", "前缀"],
    ),
    FunctionEntry(
        name="RIGHT",
        zh_name="右截取",
        category=CATEGORY_DATA,
        syntax="RIGHT(text, [num_chars])",
        description_zh="从文本右侧开始截取指定数量的字符。",
        example_zh='=RIGHT("潍坊力创电子科技",4) 返回"电子科技"',
        common_use_cases=["提取后缀", "取后几位"],
        pitfalls=["中文每个字算1个字符"],
        keywords=["right", "右截取", "取右边", "后缀"],
    ),
    FunctionEntry(
        name="MID",
        zh_name="中间截取",
        category=CATEGORY_DATA,
        syntax="MID(text, start_num, num_chars)",
        description_zh="从文本的指定位置开始截取指定数量的字符。",
        example_zh='=MID("潍坊力创电子科技",3,2) 从第3个字符开始取2个，返回"力创"',
        common_use_cases=["提取中间字符", "按位置截取"],
        pitfalls=["start_num 从1开始计数"],
        keywords=["mid", "中间截取", "取中间", "截取"],
    ),
    FunctionEntry(
        name="FIND",
        zh_name="查找位置（区分大小写）",
        category=CATEGORY_DATA,
        syntax="FIND(find_text, within_text, [start_num])",
        description_zh="在一个文本中查找另一个文本，返回其起始位置。区分大小写。",
        example_zh='=FIND("科技","潍坊力创电子科技") 返回5',
        common_use_cases=["定位字符位置", "配合LEFT/MID/RIGHT使用"],
        pitfalls=["区分大小写", "找不到返回 #VALUE!", "中文搜索时常用 SEARCH（不区分大小写）"],
        keywords=["find", "查找位置", "定位"],
    ),
    FunctionEntry(
        name="SEARCH",
        zh_name="搜索位置（不区分大小写）",
        category=CATEGORY_DATA,
        syntax="SEARCH(find_text, within_text, [start_num])",
        description_zh="与 FIND 类似，但不区分大小写，且支持通配符（?匹配单字符，*匹配任意序列）。",
        example_zh='=SEARCH("*科技","潍坊力创电子科技") 返回1（通配符匹配）',
        common_use_cases=["不区分大小写搜索", "模糊搜索位置"],
        pitfalls=["支持通配符", "不区分大小写"],
        keywords=["search", "搜索", "模糊查找"],
    ),
    FunctionEntry(
        name="TRIM",
        zh_name="清除多余空格",
        category=CATEGORY_DATA,
        syntax="TRIM(text)",
        description_zh="删除文本中多余的空格，只保留单词之间单个空格。常用于清理导入数据。",
        example_zh='=TRIM("  潍坊  力创  ") 返回"潍坊 力创"',
        common_use_cases=["清理空格", "数据清洗", "规范化文本"],
        pitfalls=["不删除不间断空格（可用 SUBSTITUTE 处理）"],
        keywords=["trim", "去空格", "清理", "空格"],
    ),
    FunctionEntry(
        name="CLEAN",
        zh_name="清除不可打印字符",
        category=CATEGORY_DATA,
        syntax="CLEAN(text)",
        description_zh="删除文本中所有不可打印字符（ASCII 0-31）。常用于清理从其他系统导出的数据。",
        example_zh="=CLEAN(A2) 清除A2中的不可见字符",
        common_use_cases=["清理换行符", "清理特殊字符"],
        pitfalls=["不删除 ASCII 127+ 的非打印字符"],
        keywords=["clean", "清理", "不可见字符", "特殊字符"],
    ),
    FunctionEntry(
        name="SUBSTITUTE",
        zh_name="文本替换",
        category=CATEGORY_DATA,
        syntax="SUBSTITUTE(text, old_text, new_text, [instance_num])",
        description_zh="将文本中的指定字符串替换为新字符串。可指定替换第几次出现的位置。",
        example_zh='=SUBSTITUTE(G5,",","") 将G5中数字的逗号去掉，如"6,000"→"6000"',
        common_use_cases=["替换字符", "删除特定字符", "清洗数据"],
        pitfalls=["区分大小写", "不指定 instance_num 则替换所有"],
        keywords=["substitute", "替换", "去除", "改成"],
    ),
    FunctionEntry(
        name="REPLACE",
        zh_name="位置替换",
        category=CATEGORY_DATA,
        syntax="REPLACE(old_text, start_num, num_chars, new_text)",
        description_zh="从指定位置开始替换指定数量的字符。基于位置而非内容。",
        example_zh='=REPLACE("13812345678",4,4,"****") 手机号中间4位替换为星号',
        common_use_cases=["脱敏处理", "按位置替换", "格式化"],
        pitfalls=["基于位置而非内容（用 SUBSTITUTE 基于内容替换）"],
        keywords=["replace", "位置替换", "脱敏", "打码"],
    ),
    FunctionEntry(
        name="CONCAT",
        zh_name="文本连接",
        category=CATEGORY_DATA,
        syntax="CONCAT(text1, [text2], ...)",
        description_zh="将多个文本或区域连接成一个文本。比 & 运算符更方便处理区域。",
        example_zh='=CONCAT(B5,"-",D5) 返回"潍坊力创电子科技-装配工"',
        common_use_cases=["拼接文本", "合并内容"],
        pitfalls=["不自动添加分隔符（需手动加入）"],
        keywords=["concat", "连接", "拼接", "合并"],
    ),
    FunctionEntry(
        name="TEXTJOIN",
        zh_name="带分隔符文本连接",
        category=CATEGORY_DATA,
        syntax="TEXTJOIN(delimiter, ignore_empty, text1, [text2], ...)",
        description_zh="使用指定分隔符连接多个文本，可选择忽略空单元格。比 CONCAT 更灵活。",
        example_zh='=TEXTJOIN("、",TRUE,D5:D10) 用顿号连接D5到D10的非空岗位名称',
        common_use_cases=["用分隔符合并", "生成列表", "拼接多个值"],
        pitfalls=["delimiter 为空字符串时直接拼接"],
        keywords=["textjoin", "分隔符连接", "拼接", "合并"],
    ),
    FunctionEntry(
        name="TEXTSPLIT",
        zh_name="文本分列",
        category=CATEGORY_DATA,
        syntax="TEXTSPLIT(text, col_delimiter, [row_delimiter], [ignore_empty], [pad_with])",
        description_zh="使用分隔符将文本拆分为多列或多行。Excel 365/WPS 新版本支持。",
        example_zh='=TEXTSPLIT("5,000-7,000","-") 将薪资范围拆分为{"5,000","7,000"}',
        common_use_cases=["分列", "拆分文本", "提取范围值"],
        pitfalls=["Excel 365+ 支持", "结果溢出到相邻单元格"],
        keywords=["textsplit", "分列", "拆分", "分隔"],
    ),
    FunctionEntry(
        name="TEXT",
        zh_name="格式化文本",
        category=CATEGORY_DATA,
        syntax="TEXT(value, format_text)",
        description_zh="将数值按指定格式转换为文本。",
        example_zh='=TEXT(G5,"#,##0") 将6000格式化为"6,000"',
        common_use_cases=["格式化数字", "日期转文本", "统一格式"],
        pitfalls=["结果变为文本（不能直接参与数值运算）"],
        keywords=["text", "格式化", "显示格式", "转换文本"],
    ),
    FunctionEntry(
        name="VALUE",
        zh_name="文本转数值",
        category=CATEGORY_DATA,
        syntax="VALUE(text)",
        description_zh="将文本格式的数字转换为数值。常配合 SUBSTITUTE 使用清理数字文本。",
        example_zh='=VALUE(SUBSTITUTE("6,000",",","")) 将"6,000"转为6000数值',
        common_use_cases=["文本数字转换", "清理后数值化"],
        pitfalls=["文本必须是可以识别为数字的格式"],
        keywords=["value", "转数值", "文本转数字"],
    ),
    FunctionEntry(
        name="IFERROR",
        zh_name="错误处理",
        category=CATEGORY_DATA,
        syntax="IFERROR(value, value_if_error)",
        description_zh="如果公式计算结果为错误值（#N/A, #VALUE!, #DIV/0!等），返回指定值；否则返回原结果。",
        example_zh='=IFERROR(VLOOKUP("不存在的公司",A5:B51,2,FALSE),"未找到")',
        common_use_cases=["错误降级", "美化表格", "VLOOKUP未找到时显示友好信息"],
        pitfalls=["会隐藏所有类型的错误（包括你不希望隐藏的），调试时慎用"],
        keywords=["iferror", "错误处理", "容错", "找不到"],
    ),
    FunctionEntry(
        name="IFNA",
        zh_name="处理 #N/A",
        category=CATEGORY_DATA,
        syntax="IFNA(value, value_if_na)",
        description_zh="只在公式返回 #N/A 时替换为指定值，其他错误（#VALUE!等）照常显示。比 IFERROR 更精准。",
        example_zh='=IFNA(VLOOKUP("不存在",A5:B51,2,FALSE),"未找到")',
        common_use_cases=["精确处理查无结果", "比IFERROR更安全的容错"],
        pitfalls=["只处理 #N/A，不处理其他错误"],
        keywords=["ifna", "处理N/A", "找不到处理"],
    ),
    FunctionEntry(
        name="FILTER",
        zh_name="筛选函数",
        category=CATEGORY_DATA,
        syntax="FILTER(array, include, [if_empty])",
        description_zh="基于条件筛选数组，返回满足条件的所有行。动态数组函数，结果自动溢出。",
        example_zh='=FILTER(A5:H51,E5:E51="一线","没有一线岗位") 筛选所有一线岗位数据',
        common_use_cases=["动态筛选", "条件提取", "多条件过滤"],
        pitfalls=["Excel 365/WPS 2021+ 支持", "结果溢出到相邻单元格"],
        keywords=["filter", "筛选", "过滤", "动态筛选"],
    ),
    FunctionEntry(
        name="SORT",
        zh_name="排序函数",
        category=CATEGORY_DATA,
        syntax="SORT(array, [sort_index], [sort_order], [by_col])",
        description_zh="对数组按指定列排序。sort_order: 1=升序（默认），-1=降序。动态数组函数。",
        example_zh="=SORT(A5:G51,7,-1) 按第7列（中位数）降序排列",
        common_use_cases=["动态排序", "自动排名表"],
        pitfalls=["Excel 365/WPS 2021+ 支持"],
        keywords=["sort", "排序", "升序", "降序", "排列"],
    ),
    FunctionEntry(
        name="UNIQUE",
        zh_name="去重",
        category=CATEGORY_DATA,
        syntax="UNIQUE(array, [by_col], [occurs_once])",
        description_zh="返回数组中的唯一值列表。可去除重复行。动态数组函数。",
        example_zh="=UNIQUE(B5:B51) 提取所有不重复的公司名称",
        common_use_cases=["去重", "提取唯一值", "生成不重复列表"],
        pitfalls=["Excel 365/WPS 2021+ 支持"],
        keywords=["unique", "去重", "唯一值", "不重复"],
    ),
    FunctionEntry(
        name="TRANSPOSE",
        zh_name="转置",
        category=CATEGORY_DATA,
        syntax="TRANSPOSE(array)",
        description_zh="将行转置为列，或将列转置为行。",
        example_zh="=TRANSPOSE(A1:H1) 将横向表头转为纵向",
        common_use_cases=["行列互换", "数据转置"],
        pitfalls=["数组公式需 Ctrl+Shift+Enter（旧版Excel）"],
        keywords=["transpose", "转置", "行列互换"],
    ),
    FunctionEntry(
        name="TEXTBEFORE",
        zh_name="分隔符前文本",
        category=CATEGORY_DATA,
        syntax="TEXTBEFORE(text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found])",
        description_zh="返回指定分隔符之前的文本。适合提取范围值的前半部分。",
        example_zh='=TEXTBEFORE(F5,"-") 从"5,000-7,000"中提取"5,000"',
        common_use_cases=["提取分隔符前内容", "拆分范围值下限"],
        pitfalls=["Excel 365/WPS 新版本支持"],
        keywords=["textbefore", "分隔符前", "提取前缀"],
    ),
    FunctionEntry(
        name="TEXTAFTER",
        zh_name="分隔符后文本",
        category=CATEGORY_DATA,
        syntax="TEXTAFTER(text, delimiter, [instance_num], [match_mode], [match_end], [if_not_found])",
        description_zh="返回指定分隔符之后的文本。",
        example_zh='=TEXTAFTER(F5,"-") 从"5,000-7,000"中提取"7,000"',
        common_use_cases=["提取分隔符后内容", "拆分范围值上限"],
        pitfalls=["Excel 365/WPS 新版本支持"],
        keywords=["textafter", "分隔符后", "提取后缀"],
    ),
    FunctionEntry(
        name="LEN",
        zh_name="文本长度",
        category=CATEGORY_DATA,
        syntax="LEN(text)",
        description_zh="返回文本字符串的字符个数。中文每个字算1个。",
        example_zh='=LEN("潍坊力创") 返回4',
        common_use_cases=["计算字符数", "配合其他函数截取"],
        keywords=["len", "长度", "字符数"],
    ),
    FunctionEntry(
        name="UPPER/LOWER/PROPER",
        zh_name="大小写转换",
        category=CATEGORY_DATA,
        syntax="UPPER(text) / LOWER(text) / PROPER(text)",
        description_zh="UPPER=全大写，LOWER=全小写，PROPER=首字母大写。英文文本规范化。",
        example_zh='=UPPER("hello") 返回"HELLO"',
        common_use_cases=["英文标准化", "大小写统一"],
        pitfalls=["中文不受影响"],
        keywords=["upper", "lower", "proper", "大写", "小写"],
    ),
    FunctionEntry(
        name="EXACT",
        zh_name="精确比较",
        category=CATEGORY_DATA,
        syntax="EXACT(text1, text2)",
        description_zh="比较两个文本是否完全相同（区分大小写）。返回 TRUE 或 FALSE。",
        example_zh='=EXACT(A1,B1) 判断A1和B1是否完全一致',
        common_use_cases=["精确匹配判断", "区分大小写比较"],
        pitfalls=["区分大小写（不同于 = 运算符）"],
        keywords=["exact", "精确比较", "严格匹配"],
    ),
    FunctionEntry(
        name="DATE",
        zh_name="构造日期",
        category=CATEGORY_DATA,
        syntax="DATE(year, month, day)",
        description_zh="根据年、月、日数值构造一个日期。",
        example_zh="=DATE(2026,7,19) 返回2026年7月19日",
        common_use_cases=["构造日期", "日期计算"],
        pitfalls=["month 超出12会自动进位"],
        keywords=["date", "日期", "构造日期"],
    ),
    FunctionEntry(
        name="DATEDIF",
        zh_name="日期差",
        category=CATEGORY_DATA,
        syntax="DATEDIF(start_date, end_date, unit)",
        description_zh="计算两个日期之间的差值。unit: Y=年, M=月, D=天, YM=同年月差, MD=同月天差, YD=同年天差。",
        example_zh='=DATEDIF(A1,TODAY(),"Y") 计算从A1日期到今天有几周年',
        common_use_cases=["计算工龄", "年龄计算", "天数差"],
        pitfalls=["Excel 隐藏函数（无自动补全）", "start_date 必须小于 end_date"],
        keywords=["datedif", "日期差", "工龄", "年龄", "相隔天数"],
    ),
    FunctionEntry(
        name="TODAY",
        zh_name="今天日期",
        category=CATEGORY_DATA,
        syntax="TODAY()",
        description_zh="返回当前日期（动态更新）。",
        example_zh="=TODAY() 返回今天的日期",
        common_use_cases=["动态日期", "计算天数差", "自动时间戳"],
        pitfalls=["每次打开文件都会更新"],
        keywords=["today", "今天", "当前日期"],
    ),
    FunctionEntry(
        name="NOW",
        zh_name="当前日期时间",
        category=CATEGORY_DATA,
        syntax="NOW()",
        description_zh="返回当前日期和时间。",
        example_zh="=NOW() 返回当前日期和时间",
        common_use_cases=["时间戳", "动态时间"],
        pitfalls=["每次重新计算都会更新"],
        keywords=["now", "现在", "当前时间"],
    ),
    FunctionEntry(
        name="YEAR/MONTH/DAY",
        zh_name="提取年月日",
        category=CATEGORY_DATA,
        syntax="YEAR(date) / MONTH(date) / DAY(date)",
        description_zh="从日期中分别提取年、月、日。",
        example_zh="=YEAR(TODAY()) 返回2026",
        common_use_cases=["提取日期分量", "按年/月分组"],
        pitfalls=["日期需为有效的日期序列值"],
        keywords=["year", "month", "day", "年", "月", "日"],
    ),
    FunctionEntry(
        name="EOMONTH",
        zh_name="月末日期",
        category=CATEGORY_DATA,
        syntax="EOMONTH(start_date, months)",
        description_zh="返回指定日期之前或之后几个月的最后一天。",
        example_zh="=EOMONTH(TODAY(),0) 返回本月最后一天",
        common_use_cases=["计算月末", "到期日", "结算日"],
        pitfalls=["months=0返回当月最后一天"],
        keywords=["eomonth", "月末", "月底", "最后一天"],
    ),
    FunctionEntry(
        name="WORKDAY",
        zh_name="工作日计算",
        category=CATEGORY_DATA,
        syntax="WORKDAY(start_date, days, [holidays])",
        description_zh="返回指定工作日数之前或之后的日期（排除周末）。",
        example_zh="=WORKDAY(TODAY(),10) 10个工作日后的日期",
        common_use_cases=["计算截止日", "工作日推算", "项目排期"],
        pitfalls=["默认只排除周六日，需排除节假日用holidays参数"],
        keywords=["workday", "工作日", "截止日"],
    ),
    FunctionEntry(
        name="NETWORKDAYS",
        zh_name="工作日天数",
        category=CATEGORY_DATA,
        syntax="NETWORKDAYS(start_date, end_date, [holidays])",
        description_zh="计算两个日期之间的工作日天数（排除周末）。",
        example_zh="=NETWORKDAYS(DATE(2026,7,1),DATE(2026,7,31)) 计算7月有多少工作日",
        common_use_cases=["计算工日", "出勤天数", "项目天数"],
        pitfalls=["默认只排除周六日"],
        keywords=["networkdays", "工作日天数", "出勤"],
    ),
    FunctionEntry(
        name="WEEKNUM",
        zh_name="第几周",
        category=CATEGORY_DATA,
        syntax="WEEKNUM(date, [return_type])",
        description_zh="返回日期在一年中的第几周。",
        example_zh="=WEEKNUM(TODAY()) 今天是一年中的第几周",
        common_use_cases=["按周汇总", "周报", "周次"],
        pitfalls=["return_type 影响周起始日"],
        keywords=["weeknum", "第几周", "周次"],
    ),
    FunctionEntry(
        name="CHOOSE",
        zh_name="选择函数",
        category=CATEGORY_DATA,
        syntax="CHOOSE(index_num, value1, [value2], ...)",
        description_zh="根据索引号从列表中选择对应的值。index_num 从1开始。",
        example_zh='=CHOOSE(2,"一线","技术","职能") 返回"技术"',
        common_use_cases=["按序号选择", "序号转文本"],
        pitfalls=["index_num 必须在 1-254 之间"],
        keywords=["choose", "选择", "按序号"],
    ),
    FunctionEntry(
        name="ISNUMBER",
        zh_name="判断是否为数字",
        category=CATEGORY_DATA,
        syntax="ISNUMBER(value)",
        description_zh="判断一个值是否为数字，返回 TRUE 或 FALSE。常用于数据验证。",
        example_zh="=ISNUMBER(G5) 判断G5是否为数字",
        common_use_cases=["数据验证", "判断数值"],
        pitfalls=["文本格式的数字返回FALSE"],
        keywords=["isnumber", "判断数字", "验证"],
    ),
    FunctionEntry(
        name="ISTEXT",
        zh_name="判断是否为文本",
        category=CATEGORY_DATA,
        syntax="ISTEXT(value)",
        description_zh="判断一个值是否为文本。",
        example_zh="=ISTEXT(B5) 判断B5是否为文本",
        common_use_cases=["数据验证", "类型判断"],
        keywords=["istext", "判断文本"],
    ),
    FunctionEntry(
        name="ISBLANK",
        zh_name="判断是否为空",
        category=CATEGORY_DATA,
        syntax="ISBLANK(value)",
        description_zh="判断单元格是否为空，返回 TRUE 或 FALSE。",
        example_zh="=ISBLANK(A1) 判断A1是否为空",
        common_use_cases=["检查空值", "数据完整性"],
        pitfalls=["包含空字符串的单元格返回FALSE"],
        keywords=["isblank", "是否为空", "空值检查"],
    ),
    FunctionEntry(
        name="INDIRECT",
        zh_name="间接引用",
        category=CATEGORY_DATA,
        syntax="INDIRECT(ref_text, [a1])",
        description_zh="返回文本字符串指定的引用。可以根据其他单元格的值动态改变引用目标。",
        example_zh='=INDIRECT("G"&ROW()) 动态引用G列当前行',
        common_use_cases=["动态引用", "跨表引用", "下拉菜单联动"],
        pitfalls=["是易失性函数（任何单元格变化都会重新计算）", "被引用的工作簿必须打开"],
        keywords=["indirect", "间接引用", "动态引用"],
    ),
    FunctionEntry(
        name="OFFSET",
        zh_name="偏移引用",
        category=CATEGORY_DATA,
        syntax="OFFSET(reference, rows, cols, [height], [width])",
        description_zh="以指定引用为基准，偏移指定行列数后返回新引用。可指定返回区域的高度和宽度。",
        example_zh="=OFFSET(A1,4,6) 从A1向下偏移4行、向右偏移6列，即G5",
        common_use_cases=["动态范围", "滚动汇总"],
        pitfalls=["易失性函数", "可能造成循环引用"],
        keywords=["offset", "偏移", "动态区域"],
    ),
    FunctionEntry(
        name="HYPERLINK",
        zh_name="超链接",
        category=CATEGORY_DATA,
        syntax="HYPERLINK(link_location, [friendly_name])",
        description_zh="创建一个可点击的超链接。",
        example_zh='=HYPERLINK("https://www.example.com","点击访问")',
        common_use_cases=["创建链接", "跳转"],
        keywords=["hyperlink", "超链接", "链接"],
    ),
]


# ============================================================
# 聚合所有函数
# ============================================================

ALL_FUNCTIONS: list[FunctionEntry] = STATS_FUNCTIONS + FINANCE_FUNCTIONS + DATA_FUNCTIONS


def get_functions_by_category(category: str) -> list[FunctionEntry]:
    """按分类获取函数列表。"""
    return [f for f in ALL_FUNCTIONS if f.category == category]


def search_functions(query: str, top_k: int = 5) -> list[FunctionEntry]:
    """关键词搜索函数（匹配名称、中文名、关键词、用例）。返回最相关的 top_k 个。"""
    query_lower = query.lower()
    scored: list[tuple[int, FunctionEntry]] = []

    for func in ALL_FUNCTIONS:
        score = 0
        # 精确匹配名称
        if query_lower == func.name.lower():
            score += 100
        # 关键词匹配
        for kw in func.keywords:
            if query_lower in kw.lower() or kw.lower() in query_lower:
                score += 20
        # 用例匹配
        for case in func.common_use_cases:
            if any(word in case for word in query_lower.split()):
                score += 10
        # 中文名匹配
        if query_lower in func.zh_name:
            score += 30

        if score > 0:
            scored.append((score, func))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [f for _, f in scored[:top_k]]


def get_function_by_name(name: str) -> Optional[FunctionEntry]:
    """按英文名精确查找函数。"""
    name_upper = name.upper()
    for func in ALL_FUNCTIONS:
        if func.name.upper() == name_upper:
            return func
    return None
